"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

import os

# Always allow your Railway domain (safe + simple)
DEFAULT_ALLOWED = ["heardrum-production.up.railway.app", "localhost", "127.0.0.1"]

hosts = os.getenv("ALLOWED_HOSTS", "")
if hosts:
    ALLOWED_HOSTS = [h.strip() for h in hosts.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = DEFAULT_ALLOWED



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-secret")
DEBUG = os.getenv("DEBUG", "False").lower() == "true"




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'core',
    'corsheaders'
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def env_value(name, default=""):
    return os.getenv(name) or default


def database_config_from_url(database_url):
    parsed = urlparse(database_url)
    engine_by_scheme = {
        "postgres": "django.db.backends.postgresql",
        "postgresql": "django.db.backends.postgresql",
        "postgresql+psycopg": "django.db.backends.postgresql",
    }
    engine = engine_by_scheme.get(parsed.scheme)
    if not engine:
        return None

    config = {
        "ENGINE": engine,
        "NAME": unquote(parsed.path.lstrip("/")),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or ""),
    }
    options = {
        key: value
        for key, value in parse_qsl(parsed.query)
        if key in {"sslmode", "service"}
    }
    if options:
        config["OPTIONS"] = options
    return config


database_url = env_value("DATABASE_URL")
railway_database = database_config_from_url(database_url) if database_url else None

DATABASES = {
    "default": railway_database
    or {
        "ENGINE": env_value("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": env_value("DB_NAME", env_value("PGDATABASE", "heardrum")),
        "USER": env_value("DB_USER", env_value("PGUSER", "postgres")),
        "PASSWORD": env_value("DB_PASSWORD", env_value("PGPASSWORD", "")),
        "HOST": env_value("DB_HOST", env_value("PGHOST", "localhost")),
        "PORT": env_value("DB_PORT", env_value("PGPORT", "6767")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
}

AMBIENT_MODEL_PATH = os.getenv(
    "AMBIENT_MODEL_PATH",
    str(BASE_DIR / "core" / "ml" / "models" / "ambient_cnn.pt"),
)
AMBIENT_MODEL_DEVICE = os.getenv("AMBIENT_MODEL_DEVICE") or None
AMBIENT_AUDIO_MAX_UPLOAD_BYTES = int(
    os.getenv("AMBIENT_AUDIO_MAX_UPLOAD_BYTES", str(4 * 1024 * 1024))
)
AMBIENT_AUDIO_MIN_SECONDS = float(os.getenv("AMBIENT_AUDIO_MIN_SECONDS", "1.0"))
AMBIENT_AUDIO_MAX_SECONDS = float(os.getenv("AMBIENT_AUDIO_MAX_SECONDS", "8.0"))

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://heardrum.vercel.app"
]


