# Generated by Django 5.2.8 on 2026-09-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('connection', models.CharField(choices=[('wired', 'Wired'), ('wireless', 'Wireless'), ('both', 'Both')], max_length=20)),
                ('max_db_spl_wired', models.CharField(blank=True, max_length=150, null=True)),
                ('max_db_spl_bluetooth', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
