# Generated by Django 5.2.8 on 2026-09-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_listeningsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeningsession",
            name="ambient_analysis_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="ambient_environment_class",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="ambient_confidence",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
