# Generated by Django 5.2.8 on 2026-09-30

import django.core.validators
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_listeningsession_ambient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="listeningsession",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="last_resumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="paused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="accumulated_duration_seconds",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="exposure_percent",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddConstraint(
            model_name="listeningsession",
            constraint=models.UniqueConstraint(
                condition=Q(("status__in", ["active", "paused"])),
                fields=("user",),
                name="one_unfinished_listening_session_per_user",
            ),
        ),
    ]
